/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.85
 * Generated at: 2024-02-29 07:51:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_005fform_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/css/login.css\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"container\" id=\"container\">\r\n");
      out.write("  <!-- 회원가입 -->\r\n");
      out.write("  <div class=\"form-container sign-up-container\">\r\n");
      out.write("    <form>\r\n");
      out.write("      <h1>Create Account</h1>\r\n");
      out.write("      <div class=\"social-container\">\r\n");
      out.write("        <a href=\"#\" onclick=\"location.href='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${urlNaver}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'\" class=\"social\"><img src=\"resources/img/NaverBtn.png\" ></a>\r\n");
      out.write("        <a href=\"https://kauth.kakao.com/oauth/authorize?client_id=abc320a5a43005c6fe87b9f765fda4cb&redirect_uri=http://localhost:9090/board/kakaoLogin&response_type=code\">\r\n");
      out.write("        	<img src=\"resources/img/KakaoBtn.png\"></a>\r\n");
      out.write("      </div>\r\n");
      out.write("      <span>or use your email for registration</span>\r\n");
      out.write("	    <input type=\"text\" name=\"user_name\" id=\"user_name\"  oninput=\"checkName(this.form)\" placeholder=\"Name\" /><span style='color:red;'id=\"check_name\"></span>\r\n");
      out.write("		<input type=\"email\" name=\"user_email\" id=\"user_email\" oninput=\"checkEmail(this.form)\" placeholder=\"Email\" /><span style='color:green;'id=\"check_email\"></span>\r\n");
      out.write("		<input type=\"password\" name=\"user_pw\" id=\"user_pw\"  oninput=\"checkPw(this.form)\" placeholder=\"Password\" /><span style='color:red;' id=\"check_pw\"></span>\r\n");
      out.write("      <button type = \"button\" onclick=\"send(this.form)\">Sign Up</button>\r\n");
      out.write("    </form>\r\n");
      out.write("  </div>\r\n");
      out.write("  \r\n");
      out.write("  <!-- 로그인 -->\r\n");
      out.write("  <div class=\"form-container sign-in-container\">\r\n");
      out.write("    <form>\r\n");
      out.write("      <h1>Sign in</h1>\r\n");
      out.write("      <div class=\"social-container\">\r\n");
      out.write("        <a href=\"#\" onclick=\"location.href='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${urlNaver}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'\" class=\"social\"><img src=\"resources/img/NaverBtn.png\" ></a>\r\n");
      out.write("        <a href=\"https://kauth.kakao.com/oauth/authorize?client_id=abc320a5a43005c6fe87b9f765fda4cb&redirect_uri=http://localhost:9090/board/kakaoLogin&response_type=code\">\r\n");
      out.write("        	<img src=\"resources/img/KakaoBtn.png\"></a>\r\n");
      out.write("      </div>\r\n");
      out.write("      <span>or use your account</span>\r\n");
      out.write("      <input type=\"email\" name=\"user_email\" id=\"login_email\" oninput=\"LoginCheckEmail(this.form)\" placeholder=\"Email\" /><span style='color:red;'id=\"checklog_email\"></span>\r\n");
      out.write("      <input type=\"password\"name=\"user_pw\" id=\"login_pw\"  oninput=\"LoginCheckPw(this.form)\" placeholder=\"Password\" /><span style='color:red;' id=\"checklog_pw\"></span>\r\n");
      out.write("      <!-- 추가 구현 비밀번호 -->\r\n");
      out.write("      <a href=\"#\">Forgot your password?</a>\r\n");
      out.write("   	  <button type = \"button\"onclick=\"login(this.form)\">Sign In</button>\r\n");
      out.write("    </form>\r\n");
      out.write("  </div>\r\n");
      out.write("  \r\n");
      out.write("  <!-- 회원가입 / 로그인 사이드바  -->\r\n");
      out.write("  <div class=\"overlay-container\">\r\n");
      out.write("    <div class=\"overlay\">\r\n");
      out.write("      <div class=\"overlay-panel overlay-left\">\r\n");
      out.write("        <h1>Welcome Back!</h1>\r\n");
      out.write("        <p>세상에 하나뿐인 특별한 프로젝트를\r\n");
      out.write("        발견해보세요!</p>\r\n");
      out.write("        <button class=\"ghost\" id=\"signIn\">Sign In</button>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"overlay-panel overlay-right\">\r\n");
      out.write("        <h1>이메일로 가입하기</h1>\r\n");
      out.write("      	<p>후원을 기다리는 창작자를 만나보세요!</p>\r\n");
      out.write("        <button class=\"ghost\" id=\"signUp\">Sign Up</button>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("<script src=\"https://use.fontawesome.com/releases/v5.2.0/js/all.js\"></script>\r\n");
      out.write("<script src=\"https://static.nid.naver.com/js/naverLogin_implicit-1.0.2.js\" charset=\"utf-8\"></script>\r\n");
      out.write("<script src=\"http://code.jquery.com/jquery-1.11.3.min.js\"></script>\r\n");
      out.write("<script src=\"resources/js/httpRequest.js\"></script>\r\n");
      out.write("<script src=\"resources/js/login.js\"></script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
