SELECT A.*
		FROM (SELECT A.*, B.LIKE_COUNT, RANK() OVER (ORDER BY B.LIKE_COUNT DESC, A.PROJECT_IDX ASC) AS "RANK_NO" 
        FROM EF_PROJECT A, (SELECT A.PROJECT_IDX, 
                            COUNT(B.PROJECT_IDX) AS "LIKE_COUNT"
                            FROM EF_PROJECT A LEFT JOIN EF_LIKE B 
                            ON A.PROJECT_IDX = B.PROJECT_IDX
                            GROUP BY A.PROJECT_IDX) B
        WHERE A.PROJECT_IDX = B.PROJECT_IDX) A
		WHERE A.RANK_NO BETWEEN 1 AND 10;
        

SELECT count(A.project_idx)
		FROM ((SELECT A.*, B.LIKE_COUNT, RANK() OVER (ORDER BY B.LIKE_COUNT DESC, A.PROJECT_IDX ASC) AS "RANK_NO" 
        FROM EF_PROJECT A, (SELECT A.PROJECT_IDX, COUNT(B.PROJECT_IDX) AS "LIKE_COUNT"
                            FROM EF_PROJECT A
                            LEFT JOIN EF_LIKE B ON A.PROJECT_IDX = B.PROJECT_IDX
                            GROUP BY A.PROJECT_IDX) B
        WHERE A.PROJECT_IDX = B.PROJECT_IDX) A ) A, (SELECT A.PROJECT_IDX, 
        
        
