/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.85
 * Generated at: 2024-02-29 09:40:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.profile;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class charge_005fview_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("  		<!-- jQuery -->\r\n");
      out.write("        <script type=\"text/javascript\" src=\"https://code.jquery.com/jquery-1.12.4.min.js\" ></script>\r\n");
      out.write("        <!-- iamport.payment.js -->\r\n");
      out.write("        <script type=\"text/javascript\" src=\"https://cdn.iamport.kr/js/iamport.payment-1.2.0.js\"></script>\r\n");
      out.write("        <script>\r\n");
      out.write("          var IMP = window.IMP; \r\n");
      out.write("          IMP.init(\"imp52373275\"); \r\n");
      out.write("        \r\n");
      out.write("          var today = new Date();   \r\n");
      out.write("          var hours = today.getHours(); // 시\r\n");
      out.write("          var minutes = today.getMinutes();  // 분\r\n");
      out.write("          var seconds = today.getSeconds();  // 초\r\n");
      out.write("          var milliseconds = today.getMilliseconds();\r\n");
      out.write("          var makeMerchantUid = hours +  minutes + seconds + milliseconds;\r\n");
      out.write("          \r\n");
      out.write("  \r\n");
      out.write("          function requestPay() {\r\n");
      out.write("        	  if(confirm('결제하시겠습니까?')){\r\n");
      out.write("        		  let payment = document.getElementById(\"payment\").value;\r\n");
      out.write("                  IMP.request_pay({\r\n");
      out.write("                      pg : 'kakaopay',\r\n");
      out.write("                      merchant_uid: \"IMP\"+makeMerchantUid, \r\n");
      out.write("                      name : '컴퓨터',\r\n");
      out.write("                      amount : Number(payment),\r\n");
      out.write("                      buyer_email : 'tyghqkr456@naver.com',\r\n");
      out.write("                      buyer_name : '석진',\r\n");
      out.write("                      buyer_tel : '010-1234-5678',\r\n");
      out.write("                      buyer_addr : '인천광역시 부평',\r\n");
      out.write("                      buyer_postcode : '123-456'\r\n");
      out.write("                  }, function (rsp) { // callback\r\n");
      out.write("                      if (rsp.success) {\r\n");
      out.write("                          console.log(rsp);\r\n");
      out.write("                          alert('결제완료');\r\n");
      out.write("                      } else {\r\n");
      out.write("                          console.log(rsp);\r\n");
      out.write("                          alert('결제실패');\r\n");
      out.write("                      }\r\n");
      out.write("                  });\r\n");
      out.write("        	  }\r\n");
      out.write("        	 \r\n");
      out.write("          }\r\n");
      out.write("      </script>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("\r\n");
      out.write("    <title>Cyborg - Awesome HTML5 Template</title>\r\n");
      out.write("\r\n");
      out.write("    <link href=\"resources/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"resources/css/fontawesome.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"resources/css/templatemo-cyborg-gaming.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"resources/css/owl.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"resources/css/animate.css\">\r\n");
      out.write("    <link rel=\"stylesheet\"href=\"https://unpkg.com/swiper@7/swiper-bundle.min.css\"/>\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    \r\n");
      out.write("    <style>\r\n");
      out.write("          .category {\r\n");
      out.write("          display: none; /* 초기에는 숨겨진 상태 */\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("    .heading-section th {\r\n");
      out.write("      color: white;\r\n");
      out.write("      font-size: 34px;\r\n");
      out.write("      text-decoration: none;\r\n");
      out.write("      margin-bottom: 30px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    th {\r\n");
      out.write("    color: white;\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("      padding: 10px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* 테이블 셀 경계 선 스타일링 */\r\n");
      out.write("    td, th {\r\n");
      out.write("    border: 1px solid #ddd;\r\n");
      out.write("    padding: 8px;\r\n");
      out.write("    text-align: left;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    table{border:1px solid white; \r\n");
      out.write("		      border-collapse:collapse;\r\n");
      out.write("		      text-align:center;}\r\n");
      out.write("		      \r\n");
      out.write("		th{width:80px;}\r\n");
      out.write("\r\n");
      out.write("  .button-container {\r\n");
      out.write("       margin-right: 20%; /* 버튼을 오른쪽에 정렬 */\r\n");
      out.write("      margin-bottom: 20px; /* 버튼과 다음 섹션 사이의 간격 설정 */\r\n");
      out.write("   }\r\n");
      out.write("\r\n");
      out.write(".payment-button {\r\n");
      out.write("  margin-left: 0px;\r\n");
      out.write("  background-color: #FFEB3B; /* 배경색을 변경합니다. */\r\n");
      out.write("  color: #000; /* 텍스트 색상을 변경합니다. */\r\n");
      out.write("  border: none;\r\n");
      out.write("  padding: 5px 15px; /* 내부 여백을 조정합니다. */\r\n");
      out.write("  border-radius: 5px;\r\n");
      out.write("  cursor: pointer;\r\n");
      out.write("  transition: background-color 0.5s; /* 마우스 오버 시 부드럽게 변화하도록 설정합니다. */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".payment-button img {\r\n");
      out.write("  width: 100px; /* 이미지의 너비를 조정합니다. */\r\n");
      out.write("  height: auto; /* 이미지의 높이를 자동으로 조정합니다. */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#KG이니시스 {\r\n");
      out.write("      width: 100px; /* 버튼의 너비를 조정합니다. */\r\n");
      out.write("      border-radius:15px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .payment-button:not(:last-child) {\r\n");
      out.write("      margin-right: 20px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("#recharge {\r\n");
      out.write("  margin-left: 0px;\r\n");
      out.write("  background-color: #bb4ab1; /* 배경색을 변경합니다. */\r\n");
      out.write("  color: #fff; /* 텍스트 색상을 변경합니다. */\r\n");
      out.write("  border: none;\r\n");
      out.write("  padding: 5px 23px; /* 내부 여백을 조정합니다. */\r\n");
      out.write("  border-radius: 5px;\r\n");
      out.write("  cursor: pointer;\r\n");
      out.write("  transition: background-color 0.5s; /* 마우스 오버 시 부드럽게 변화하도록 설정합니다. */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#recharge:hover {\r\n");
      out.write("  background-color: #a400b3; /* 마우스 오버 시 배경색을 변경합니다. */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("  <div id=\"js-preloader\" class=\"js-preloader\">\r\n");
      out.write("    <div class=\"preloader-inner\">\r\n");
      out.write("      <span class=\"dot\"></span>\r\n");
      out.write("      <div class=\"dots\">\r\n");
      out.write("        <span></span>\r\n");
      out.write("        <span></span>\r\n");
      out.write("        <span></span>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <header class=\"header-area header-sticky\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <div class=\"col-12\">\r\n");
      out.write("                <nav class=\"main-nav\">\r\n");
      out.write("                    <a href=\"index.html\" class=\"logo\">\r\n");
      out.write("                        <img src=\"resources/images/logo.png\" alt=\"\">\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <div class=\"search-input\">\r\n");
      out.write("                      <form id=\"search\" action=\"#\">\r\n");
      out.write("                        <input type=\"text\" placeholder=\"검색\" id='searchText' name=\"searchKeyword\" onkeypress=\"handle\" />\r\n");
      out.write("                        <i class=\"fa fa-search\"></i>\r\n");
      out.write("                      </form>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <ul class=\"nav\">\r\n");
      out.write("                        <li><a href=\"index.html\">Home</a></li>\r\n");
      out.write("                        <li><a href=\"browse.html\">Browse</a></li>\r\n");
      out.write("                        <li><a href=\"details.html\">Details</a></li>\r\n");
      out.write("                        <li><a href=\"streams.html\">Streams</a></li>\r\n");
      out.write("                        <li><a href=\"mypage_view\" class=\"active\">마이페이지 <img src=\"resources/images/profile-header.jpg\" alt=\"\"></a></li>\r\n");
      out.write("                    </ul>   \r\n");
      out.write("                    <a class='menu-trigger'>\r\n");
      out.write("                        <span>Menu</span>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </nav>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </header>\r\n");
      out.write("  <div class=\"container\">\r\n");
      out.write("    <div class=\"row\">\r\n");
      out.write("      <div class=\"col-lg-12\">\r\n");
      out.write("        <div class=\"page-content\">\r\n");
      out.write("            <div id=\"profile-settings\" style=\"margin:auto\">\r\n");
      out.write("                <h2>결제 수단 방법</h2><br>\r\n");
      out.write("                <div class=\"button-container\">\r\n");
      out.write("                    <p>결제 금액</p>\r\n");
      out.write("                    <input type=\"number\"placeholder=\"숫자만 입력가능.\" id=\"payment\">\r\n");
      out.write("                </div>\r\n");
      out.write("                 <button onclick=\"requestPay()\" id=\"kakao-pay\" class=\"payment-button\">\r\n");
      out.write("                  <img src=\"./resources/images/카카오페이.jpg\" alt=\"카카오페이\">\r\n");
      out.write("                </button>\r\n");
      out.write("                <button id=\"KG이니시스\" class=\"KG이니시스\">\r\n");
      out.write("                <img src=\"./resources/images/KG이니시스.jpg\" alt=\"KG이니시스\">\r\n");
      out.write("              </button>\r\n");
      out.write("              </div><br>\r\n");
      out.write("            </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  <footer>\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <div class=\"row\">\r\n");
      out.write("        <div class=\"col-lg-12\">\r\n");
      out.write("          <p>Copyright © 2036 <a href=\"#\">Cyborg Gaming</a> Company. All rights reserved. \r\n");
      out.write("          \r\n");
      out.write("          <br>Design: <a href=\"https://templatemo.com\" target=\"_blank\" title=\"free CSS templates\">TemplateMo</a>  Distributed By <a href=\"https://themewagon.com\" target=\"_blank\" >ThemeWagon</a></p>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </footer>\r\n");
      out.write("\r\n");
      out.write("  <script src=\"resources/jquery/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"resources/js/bootstrap.min.js\"></script>\r\n");
      out.write("  <script src=\"resources/js/isotope.min.js\"></script>\r\n");
      out.write("  <script src=\"resources/js/owl-carousel.js\"></script>\r\n");
      out.write("  <script src=\"resources/js/tabs.js\"></script>\r\n");
      out.write("  <script src=\"resources/js/popup.js\"></script>\r\n");
      out.write("  <script src=\"resources/js/custom.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
