/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.85
 * Generated at: 2024-02-29 10:11:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.profile;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class mypage_005fview_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("    <title>Cyborg - Awesome HTML5 Template</title>\r\n");
      out.write("    \r\n");
      out.write("    <link href=\"resources//css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"resources/css/fontawesome.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"resources/css/templatemo-cyborg-gaming.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"resources/css/owl.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"resources/css/animate.css\">\r\n");
      out.write("    <link rel=\"stylesheet\"href=\"https://unpkg.com/swiper@7/swiper-bundle.min.css\"/>\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <style>\r\n");
      out.write("      .heading-section h4 {\r\n");
      out.write("        color: white;\r\n");
      out.write("        font-size: 34px;\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("        margin-bottom: 30px;\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("       .owl-features .item {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    float: left; /* 좌측 정렬되도록 함 */\r\n");
      out.write("   }\r\n");
      out.write("\r\n");
      out.write("  .owl-features .thumb img {\r\n");
      out.write("    width: 100%; /* 각 사진 이미지가 요소 내에 꽉 차게 표시되도록 함 */\r\n");
      out.write("    border-radius: 20px;\r\n");
      out.write("  	}\r\n");
      out.write("  .down-content .down-content span {\r\n");
      out.write("    padding: 10px 0; /* 위아래 padding을 조절하여 높이를 조절합니다 */\r\n");
      out.write("    display: flex;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("    </style>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("  <div id=\"js-preloader\" class=\"js-preloader\">\r\n");
      out.write("    <div class=\"preloader-inner\">\r\n");
      out.write("      <span class=\"dot\"></span>\r\n");
      out.write("      <div class=\"dots\">\r\n");
      out.write("        <span></span>\r\n");
      out.write("        <span></span>\r\n");
      out.write("        <span></span>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <header class=\"header-area header-sticky\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <div class=\"col-12\">\r\n");
      out.write("                <nav class=\"main-nav\">\r\n");
      out.write("                    <a href=\"index.html\" class=\"logo\">\r\n");
      out.write("                        <img src=\"resources/images/logo.png\" alt=\"\">\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <div class=\"search-input\">\r\n");
      out.write("                      <form id=\"search\" action=\"#\">\r\n");
      out.write("                        <input type=\"text\" placeholder=\"검색\" id='searchText' name=\"searchKeyword\" onkeypress=\"handle\" />\r\n");
      out.write("                        <i class=\"fa fa-search\"></i>\r\n");
      out.write("                      </form>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <ul class=\"nav\">\r\n");
      out.write("                        <li><a href=\"index.html\">Home</a></li>\r\n");
      out.write("                        <li><a href=\"browse.html\">Browse</a></li>\r\n");
      out.write("                        <li><a href=\"details.html\">Details</a></li>\r\n");
      out.write("                        <li><a href=\"streams.html\">Streams</a></li>\r\n");
      out.write("                        <li><a href=\"mypage_view\" class=\"active\">마이페이지 <img src=\"resources/images/profile-header.jpg\" alt=\"\"></a></li>\r\n");
      out.write("                    </ul>   \r\n");
      out.write("                    <a class='menu-trigger'>\r\n");
      out.write("                        <span>Menu</span>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </nav>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </header>\r\n");
      out.write("  <div class=\"container\">\r\n");
      out.write("    <div class=\"row\">\r\n");
      out.write("      <div class=\"col-lg-12\">\r\n");
      out.write("        <div class=\"page-content\">\r\n");
      out.write("          <div class=\"row\">\r\n");
      out.write("            <div class=\"col-lg-12\">\r\n");
      out.write("              <div class=\"main-profile \">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                  <div class=\"col-lg-4\">\r\n");
      out.write("                    <img src=\"resources/images/둘리의모험.jpg\" alt=\"\" style=\"border-radius: 23px;\">\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"col-lg-4 align-self-center\">\r\n");
      out.write("                    <div class=\"main-info header-text\">\r\n");
      out.write("                      <span>현재 진행중인 프로젝트</span>\r\n");
      out.write("                      <h4>아기 공룡 둘리</h4>\r\n");
      out.write("                      <p>빙하 타고 내려온 둘리의 일상</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"col-lg-4 align-self-center\">\r\n");
      out.write("                   \r\n");
      out.write("                    <ul>\r\n");
      out.write("                      <li><a href=\"myinfo_view\">내 정보</a></li>\r\n");
      out.write("                      <li>후원 누적 포인트 <span>1,100,000 Point</span></li>\r\n");
      out.write("                      <li>잔여 포인트 <span>7,000 Point</span></li>\r\n");
      out.write("                      <li><a href=\"review\">리뷰</a></li>\r\n");
      out.write("                      <li>포인트 충전\r\n");
      out.write("                        <a href=\"charge_view\">\r\n");
      out.write("                          <button id=\"recharge-button\" style=\"margin-left: 135px; background-color: #bb4ab1; color: #fff; border: none; padding: 5px 10px; border-radius: 5px; cursor: pointer; transition: background-color 0.5s;\" onmouseover=\"this.style.backgroundColor='#a400b3'\" onmouseout=\"this.style.backgroundColor='#bb4ab1'\">충전하기</button>\r\n");
      out.write("                        </a>\r\n");
      out.write("                      </li>\r\n");
      out.write("                      <li><a href=\"Sponsorshipdetails_view\">후원한 프로젝트 내역</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                  <div class=\"col-lg-12\">\r\n");
      out.write("                    <div class=\"featured-games header-text\">\r\n");
      out.write("                    <div class=\"clips\">\r\n");
      out.write("                      <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-lg-12\">\r\n");
      out.write("                          <div class=\"heading-section\">\r\n");
      out.write("                            \r\n");
      out.write("                            <h4>나의 마감된 프로젝트</h4>\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"owl-features owl-carousel\">\r\n");
      out.write("                          <div class=\"item\">\r\n");
      out.write("                            <div class=\"thumb\">\r\n");
      out.write("                              <img src=\"resources/images/귀멸의칼날01.jpg\" alt=\"\" style=\"border-radius: 23px;\">\r\n");
      out.write("                              \r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"down-content\">\r\n");
      out.write("                              <h4>귀멸의 칼날</h4>\r\n");
      out.write("                              <span><br><br><i class=\"fa fa-eye\"></i>달성 포인트 : 2,700,000 Point</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                          </div>\r\n");
      out.write("                        \r\n");
      out.write("                          <div class=\"item\">\r\n");
      out.write("                            <div class=\"thumb\">\r\n");
      out.write("                              <img src=\"resources/images/디아블로01.jpg\" alt=\"\" style=\"border-radius: 20px;\">\r\n");
      out.write("                              \r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"down-content\">\r\n");
      out.write("                              <h4>디아블로3</h4>\r\n");
      out.write("                              <span><br><br><i class=\"fa fa-eye\"></i>달성 포인트 : 4,000,000 Point</span>\r\n");
      out.write("                              \r\n");
      out.write("                            </div>\r\n");
      out.write("                          </div>\r\n");
      out.write("                        \r\n");
      out.write("                          <div class=\"item\">\r\n");
      out.write("                            <div class=\"thumb\">\r\n");
      out.write("                              <img src=\"resources/images/로스트아크01.jpg\" alt=\"\" style=\"border-radius: 23px;\">\r\n");
      out.write("                              \r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"down-content\">\r\n");
      out.write("                              <h4>로스트아크</h4>\r\n");
      out.write("                              <span><br><br><i class=\"fa fa-eye\"></i>달성 포인트 : 4,500,000 Point</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                          </div>\r\n");
      out.write("                        \r\n");
      out.write("                        \r\n");
      out.write("                          <div class=\"item\">\r\n");
      out.write("                            <div class=\"thumb\">\r\n");
      out.write("                              <img src=\"resources/images/무협01.jpg\" alt=\"\" style=\"border-radius: 23px;\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            \r\n");
      out.write("                            <div class=\"down-content\">\r\n");
      out.write("                              <h4>무협</h4>\r\n");
      out.write("                              <span><br><br><i class=\"fa fa-eye\"></i>달성 포인트 : 1,500,000 Point</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                          </div>\r\n");
      out.write("\r\n");
      out.write("                          <div class=\"item\">\r\n");
      out.write("                            <div class=\"thumb\">\r\n");
      out.write("                              <img src=\"resources/images/스타크래프트01.jpg\" alt=\"\" style=\"border-radius: 23px;\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            \r\n");
      out.write("                            <div class=\"down-content\">\r\n");
      out.write("                              <h4>스타크래프트</h4>\r\n");
      out.write("                              <span><br><br><i class=\"fa fa-eye\"></i>달성 포인트 : 6,500,000 Point</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                          </div>\r\n");
      out.write("\r\n");
      out.write("                          <div class=\"item\">\r\n");
      out.write("                            <div class=\"thumb\">\r\n");
      out.write("                              <img src=\"resources/images/검은사막01.jpg\" alt=\"\" style=\"border-radius: 23px;\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            \r\n");
      out.write("                            <div class=\"down-content\">\r\n");
      out.write("                              <h4>검은사막</h4>\r\n");
      out.write("                              <span><br><br><i class=\"fa fa-eye\"></i>달성 포인트 : 2,300,000 Point</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                          <div class=\"main-button\">\r\n");
      out.write("                            <a href=\"#\">진행중인 프로젝트 보기</a>\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div> \r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <footer>\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <div class=\"row\">\r\n");
      out.write("        <div class=\"col-lg-12\">\r\n");
      out.write("          <p>Copyright © 2036 <a href=\"#\">Cyborg Gaming</a> Company. All rights reserved. \r\n");
      out.write("          \r\n");
      out.write("          <br>Design: <a href=\"https://templatemo.com\" target=\"_blank\" title=\"free CSS templates\">TemplateMo</a>  Distributed By <a href=\"https://themewagon.com\" target=\"_blank\" >ThemeWagon</a></p>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </footer>\r\n");
      out.write("  \r\n");
      out.write("  <script src=\"resources/jquery/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"resources/bootstrap/js/bootstrap.min.js\"></script>\r\n");
      out.write("  <script src=\"resources/js/isotope.min.js\"></script>\r\n");
      out.write("  <script src=\"resources/js/owl-carousel.js\"></script>\r\n");
      out.write("  <script src=\"resources/js/tabs.js\"></script>\r\n");
      out.write("  <script src=\"resources/js/popup.js\"></script>\r\n");
      out.write("  <script src=\"resources/js/custom.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
